# Build arguments
ARG SOURCE_CODE=.
 
# Build the manager binary
FROM registry.access.redhat.com/ubi9/go-toolset:1.26@sha256:32fa030f9ee19f8ab38df8233f217c7f5d666dfa564c015dd7deeeaf57c2719e as builder
 
## Build args to be used at this step
ARG SOURCE_CODE
 
WORKDIR /workspace

COPY go.mod go.mod
COPY go.sum go.sum

RUN go mod download

# Copy the go source
COPY . .

# Build
USER root
RUN CGO_ENABLED=1 GOOS=linux GOEXPERIMENT=strictfipsruntime go build -buildvcs=false -tags strictfipsruntime -a -o manager .

FROM registry.access.redhat.com/ubi9/ubi-minimal@sha256:7c372902c8d211db2d25c8277ba534a73b92742a334874dced829a63b0f21221
 
WORKDIR /
COPY --from=builder /workspace/manager .
 
USER 65532:65532
ENTRYPOINT ["/manager"]
 
LABEL com.redhat.component="odh-model-registry-operator-container" \
      name="managed-open-data-hub/odh-model-registry-operator-rhel8" \
      description="Manages lifecycle of RHOAI Model Registry custom resources and associated Kubernetes resources" \
      summary="odh-model-registry-operator-container" \
      maintainer="['managed-open-data-hub@redhat.com']" \
      io.openshift.expose-services="" \
      io.k8s.display-name="odh-model-registry-operator-container" \
      io.k8s.description="odh-model-registry-operator" \
      com.redhat.license_terms="https://www.redhat.com/licenses/Red_Hat_Standard_EULA_20191108.pdf"
