# Build arguments
ARG SOURCE_CODE=.
 
# Build the manager binary
FROM registry.access.redhat.com/ubi9/go-toolset:1.26@sha256:5e68f09a652ac6627a83c57655e42e24575efb278b54336039c9308607fc6b21 as builder
 
## Build args to be used at this step
ARG SOURCE_CODE
 
WORKDIR /workspace

COPY go.mod go.mod
COPY go.sum go.sum

RUN go mod download

# Copy the go source
COPY . .

# Build
USER root
RUN CGO_ENABLED=1 GOOS=linux GOEXPERIMENT=strictfipsruntime go build -buildvcs=false -tags strictfipsruntime -a -o manager .
RUN bash hack/get_aihub_manifests.sh /workspace/opt/manifests-template

FROM registry.redhat.io/ubi9/ubi-minimal-pqc@sha256:3e009398a8aa8eec621393fbf308c5e622f174900e44e8d5fe224c637920924a
 
WORKDIR /
COPY --from=builder /workspace/manager .
COPY --from=builder /workspace/opt/manifests-template/ /opt/manifests-template/
 
USER 65532:65532
ENTRYPOINT ["/manager"]
 
LABEL com.redhat.component="odh-model-registry-operator-container" \
      name="managed-open-data-hub/odh-model-registry-operator-rhel8" \
      description="Manages lifecycle of RHOAI Model Registry custom resources and associated Kubernetes resources" \
      summary="odh-model-registry-operator-container" \
      maintainer="['managed-open-data-hub@redhat.com']" \
      io.openshift.expose-services="" \
      io.k8s.display-name="odh-model-registry-operator-container" \
      io.k8s.description="odh-model-registry-operator" \
      com.redhat.license_terms="https://www.redhat.com/licenses/Red_Hat_Standard_EULA_20191108.pdf"
